### PR TITLE
small tweaks

### PR DESCRIPTION
**Pull request by s-light**
-  update version info for new release
-  fix `arduino.h` to `Arduino.h` (for case-sensitive systems)
- add info about filename has to end with MP3 or WAV

### CODE REVIEW

**Comment by s-light** [comment]
@codingABI please accept and add a new release v1.0.2

**Review by codingABI — CHANGES_REQUESTED** [review]
"/SUN*MP3" does not only match for /sun.mp3. It matches also /sun1.mp3, /sunxy.mp3, /sunny.mp3... The * is a wildcard. 

=> So I think

```
* - "/SUN*MP3" for first file matching /sun*.mp3, for example a file /sun.mp3
```

would be more correct than

```
> * - "/SUN*MP3" for a file /sun.mp3
```

What do you think?

**Comment by s-light** [comment]
yeah i know its a wildcard :-)
and i think your correction is very good!
i have added it.
and also did a quick experiment on the *first* topic.
with `g_audio.playFileByName("/BELL*MP3");`
and these songs available:
- test1 
  - `BELL.mp3` 
  - `BELL0.mp3`
  `BELL0.mp3`  was played.
- test2
  - `BELL.mp3` 
  - `BELL1.mp3`
  `BELL.mp3`  was played.

**Comment by codingABI** [comment]
I will update the PDF docu and make a new realase with you changes in Github soon

**Comment by codingABI** [comment]
1.0.2 is released now. I had to change some linebreaks from your comments because doxygen, that generates the PDF docu, made a little bit trouble

**Comment by codingABI** [comment]
In your "quick experiment on the first Topic" the order in which the first file matches seems not to be in alphabetic order. 

Perhaps it is **"copy order"** (=First audio file copied to the drive will be found first, second copied will be found next and so on)? The DFR0534 uses "copy order" already in the function playFileByNumber, playPrevious, playNext…. 

Could you try to delete all files on the DFR0534 and copy BELL3.mp3 first to the DFR0534 and than copy as second file BELL.mp3 and then BELL1.mp3?

Which file is played with g_audio.playFileByName("/BELL*MP3") ?

If it is BELL1.mp3, is seems that the DFR0534 searches the files when using wildcards in function playFileByName also in "copy order" (and I would add these information to the code comments)

Thanks for you input

**Comment by s-light** [comment]
i will du the tests.

**Comment by s-light** [comment]
i just created some small test-files 
https://github.com/s-light/DFR0534/tree/playFileByName-test_order/assets/test_sounds

and copied them one after each other in this order to the board:
- `120bpm 16bars 96kbps.mp3` 32sec - 375,6k - as `bell3-mp3`
- `240bpm 16bars 96kbps.mp3` 16sec -  188,3k - as `bell.mp3`
- `300bpm 4bars 96kbps.mp3` 3s - 38,3k - as `bell1.mp3`

image

and copied together this test-sketch
https://github.com/s-light/DFR0534/blob/playFileByName-test_order/examples/playFileByName_order_test/playFileByName_order_test.ino

the output is
```
23:00:27.862 -> Ready drives: FLASH 
23:00:27.927 -> Current playing drive: FLASH
23:00:27.958 -> Total files: 3
23:00:27.958 -> Total files in directory: 3
23:00:27.958 -> First file: 1
23:00:27.958 -> play /BELL*MP3
23:00:28.119 -> fileNr: 1 name: BELL3   MP3 status: Playing
23:00:28.408 -> fileNr: 1 name: BELL3   MP3 status: Playing
23:00:28.698 -> fileNr: 1 name: BELL3   MP3 status: Playing
....
23:00:59.384 -> fileNr: 1 name: BELL3   MP3 status: Playing
23:00:59.705 -> fileNr: 1 name: BELL3   MP3 status: Playing
23:00:59.995 -> fileNr: -- name:  status: Unknown
23:01:00.548 -> fileNr: 1 name: BELL3   MP3 status: Stopped
23:01:00.843 -> fileNr: -- name: BELL3   MP3 status: Stopped
23:01:01.139 -> fileNr: 1 name: BELL3   MP3 status: Stopped
23:01:01.433 -> fileNr: 1 name: BELL3   MP3 status: Stopped
```

so your assumption that it is the copy order is correct.
i thin  it searches the *index* table just in order (and that is the copy order) ....


i have tweaked the description a little bit to reflect the findings.

**Pull request merged**
